name: Regresion Test Execution
    
run-name: ${{ github.actor}} triggered SanityTest by ${{ github.ref.name}}
    
on:
    push:
        branches:
            - main
            - QA

jobs:
    Cypress-Sanity:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              
            - name: Install All Dependencies
              run:  npm ci

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: 20

           

            - name: Run Test chrome
              run: npm run test:ci
                



              



