name: Regresion Test Execution
    
run-name: CI Run 
    
on:
    push:
        branches:
            - main
            - QA

jobs:
    Cypress-Regresion:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: '14.17.0'

            - name: Install independence
              run: |
               npm install 
               npm list

               

              



